<?php
/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/zf2 for the canonical source repository
 * @copyright Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace Zf3Bootstrap4\Form\View\Helper;

use Zend\Form\ElementInterface;
use Zend\Form\View\Helper;

class FormElement extends Helper\FormElement
{
    /**
     * Type map to view helper
     *
     * @var array
     */
    protected $typeMap
        = [
            'text' => 'zf3b4forminput',
        ];

    public function __invoke(ElementInterface $element = null)
    {
        if ($element) {
            return $this->render($element);
        }

        return $this;
    }

    public function render(ElementInterface $element)
    {
        $renderedType = $this->renderType($element);

        if ($renderedType !== null) {
            return $renderedType;
        }

        return parent::render($element); // TODO: Change the autogenerated stub
    }

    protected function renderType(ElementInterface $element)
    {
        $type = $element->getAttribute('type');

        if (isset($this->typeMap[$type])) {
            return $this->renderHelper($this->typeMap[$type], $element);
        }
        return;
    }

    public function getLabelHelper()
    {
        if (!$this->labelHelper) {
            $this->setLabelHelper($this->view->plugin('formlabel'));
        }

        return $this->labelHelper;
    }

    public function setLabelHelper(FormLabel $labelHelper): FormElement
    {
        $labelHelper->setView($this->getView());
        $this->labelHelper = $labelHelper;

        return $this;
    }
}
